language: c
sudo: required
before_install:
  - echo 'before install' && pwd && ls
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_0f64f26238f6_key -iv $encrypted_0f64f26238f6_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - cp ssh_config ~/.ssh/config
  - git config --global user.email "dvorak4tzx@qq.com"
  - git config --global user.name "TANG ZhiXiong"
install:
  - cd ~
  - wget https://github.com/jgm/pandoc/releases/download/1.17/pandoc-1.17-1-amd64.deb
  - sudo dpkg -i pandoc*.deb
  - # wget http://devtools.qiniu.com/qiniu-devtools-linux_amd64-current.tar.gz
  - # tar xfz qiniu-devtools-linux_amd64-current.tar.gz
  - wget http://whudoc.qiniudn.com/2016/qrsync.tar.gz
  - tar xfz qrsync.tar.gz
  - chmod +x qrsync
  - sudo cp qrsync /bin
  - git clone https://github.com/district10/aha.git
  - cd aha && make && sudo make install
script:
  - cd ~/build/district10/blog;
  - cat conf.json.in | sed -e "s/QiNiuAK/$QiNiuAK/" | sed -e "s/QiNiuSK/$QiNiuSK/" > conf.json
  - make
  - make sitemap
  - # make items make move extras
  - # make filter
  - make qiniu; rm conf.json;
after_success:
  - cd ~/build/district10/blog; git reset --hard HEAD; 
  - make
  - make sitemap
  - cd publish
  - git init; git add -A; git commit -m "pushing to coding:coding-pages, lazy me @ `date`"
  - git remote add origin git@git.coding.net:dvorak4tzx/dvorak4tzx.git
  - git push -u origin HEAD:coding-pages --force
  - cd ..; rm -Rf publish; git reset --hard HEAD;
  - rm -Rf .git
  - git init; git add -A; git commit -m "pushing to coding:master, lazy me @ `date`"
  - git remote add origin git@git.coding.net:dvorak4tzx/dvorak4tzx.git
  - git push -u origin HEAD:master --force
